import type {
  InstructTemplate,
  ContextTemplate,
  SystemPrompt,
} from '../types/templates';
import type { SamplerSettings } from '../types/samplers';

export const INSTRUCT_PRESETS: Record<string, InstructTemplate> = {
  chatml: {
    input_sequence: '<|im_start|>user',
    output_sequence: '<|im_start|>assistant',
    last_output_sequence: '',
    system_sequence: '<|im_start|>system',
    stop_sequence: '<|im_end|>',
    wrap: true,
    macro: true,
    names_behavior: 'always',
    activation_regex: '',
    system_sequence_prefix: '',
    system_sequence_suffix: '',
    first_output_sequence: '',
    skip_examples: false,
    output_suffix: '<|im_end|>\n',
    input_suffix: '<|im_end|>\n',
    system_suffix: '<|im_end|>\n',
    user_alignment_message: '',
    system_same_as_user: false,
    last_system_sequence: '',
    first_input_sequence: '',
    last_input_sequence: '',
    names_force_groups: true,
    name: 'chatml',
  },
};

export const CONTEXT_PRESETS: Record<string, ContextTemplate> = {
  chatml: {
    story_string:
      "<|im_start|>system\n{{#if system}}{{system}}\n{{/if}}{{#if wiBefore}}{{wiBefore}}\n{{/if}}{{#if description}}{{description}}\n{{/if}}{{#if personality}}{{char}}'s personality: {{personality}}\n{{/if}}{{#if scenario}}Scenario: {{scenario}}\n{{/if}}{{#if wiAfter}}{{wiAfter}}\n{{/if}}{{#if persona}}{{persona}}\n{{/if}}{{trim}}<|im_end|>",
    example_separator: '',
    chat_start: '',
    use_stop_strings: false,
    allow_jailbreak: false,
    names_as_stop_strings: true,
    always_force_name2: true,
    trim_sentences: false,
    single_line: false,
    name: 'chatml',
  },
};

export const SYSTEM_PRESETS: Record<string, SystemPrompt> = {
  kusako: {
    name: 'kusako',
    content: "you're AI lol",
  },
};

export const SAMPLER_PRESETS: Record<string, SamplerSettings> = {
  default: {
    name: 'default',
    temp: 1,
    temperature_last: true,
    top_p: 0.9,
    top_k: 0,
    top_a: 0,
    tfs: 1,
    epsilon_cutoff: 0,
    eta_cutoff: 0,
    typical_p: 1,
    min_p: 0,
    rep_pen: 1,
    rep_pen_range: 0,
    rep_pen_decay: 0,
    rep_pen_slope: 1,
    no_repeat_ngram_size: 0,
    penalty_alpha: 0,
    num_beams: 1,
    length_penalty: 1,
    min_length: 0,
    encoder_rep_pen: 1,
    freq_pen: 0,
    presence_pen: 0,
    skew: 0,
    do_sample: true,
    early_stopping: false,
    dynatemp: false,
    min_temp: 0,
    max_temp: 0,
    dynatemp_exponent: 1,
    smoothing_factor: 0,
    smoothing_curve: 1,
    dry_allowed_length: 4,
    dry_multiplier: 0.8,
    dry_base: 1.75,
    dry_sequence_breakers:
      '["\\n", ":", "\\"", "*", "「", "」", "●", "`", "``", "```", "[", "]", "(", ")", "{{", "}}", "=", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]',
    dry_penalty_last_n: 0,
    add_bos_token: true,
    ban_eos_token: false,
    skip_special_tokens: true,
    mirostat_mode: 0,
    mirostat_tau: 5,
    mirostat_eta: 0.1,
    guidance_scale: 1,
    negative_prompt: '',
    grammar_string: '',
    json_schema: {},
    banned_tokens: '',
    sampler_priority: [
      'repetition_penalty',
      'presence_penalty',
      'frequency_penalty',
      'dry',
      'temperature',
      'dynamic_temperature',
      'quadratic_sampling',
      'top_k',
      'top_p',
      'typical_p',
      'epsilon_cutoff',
      'eta_cutoff',
      'tfs',
      'top_a',
      'min_p',
      'mirostat',
      'xtc',
      'encoder_repetition_penalty',
      'no_repeat_ngram',
    ],
    samplers: [
      'dry',
      'top_k',
      'tfs_z',
      'typical_p',
      'top_p',
      'min_p',
      'xtc',
      'temperature',
    ],
    samplers_priorities: [
      'dry',
      'penalties',
      'no_repeat_ngram',
      'temperature',
      'top_nsigma',
      'top_p_top_k',
      'top_a',
      'min_p',
      'tfs',
      'eta_cutoff',
      'epsilon_cutoff',
      'typical_p',
      'quadratic',
      'xtc',
    ],
    ignore_eos_token: false,
    spaces_between_special_tokens: false,
    speculative_ngram: false,
    sampler_order: [6, 0, 1, 3, 4, 2, 5],
    logit_bias: [],
    xtc_threshold: 0,
    xtc_probability: 0.5,
    nsigma: 0,
    rep_pen_size: 0,
    genamt: 1024,
    max_length: 12800,
  },
};
